/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description User created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email/username and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Logged in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description Token refreshed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout (revoke refresh token) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search anime */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    limit?: number;
                    offset?: number;
                    /** @description Comma-separated genre list */
                    genres?: string;
                    status?: string;
                    type?: string;
                    min_score?: number;
                    max_score?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Search results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watch/{episode_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get playback data for an episode (signed HLS URL) */
        get: {
            parameters: {
                query?: {
                    category?: "sub" | "dub" | "raw";
                    server?: string;
                };
                header?: never;
                path: {
                    episode_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Playback data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WatchResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activity/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert watch progress for an episode */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertProgressRequest"];
                };
            };
            responses: {
                /** @description Progress updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EpisodeProgress"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activity/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get continue-watching list */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Continue watching items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContinueWatchingResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{anime_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get streaming sources for an episode */
        get: {
            parameters: {
                query?: {
                    category?: "sub" | "dub" | "raw";
                    server?: string;
                };
                header?: never;
                path: {
                    /** @description Episode ID (passed as anime_id path param) */
                    anime_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Streaming sources */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SourcesResponse"];
                    };
                };
                /** @description Upstream resolver unavailable */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stripe/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe webhook endpoint
         * @description Receives Stripe webhook events. Verifies signature via Stripe-Signature header.
         *     Handles checkout.session.completed and invoice.paid events idempotently.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Event processed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid signature or payload */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ratings/{anime_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get rating summary for an anime */
        get: {
            parameters: {
                query?: {
                    /** @description Include user's own rating if provided */
                    user_id?: string;
                };
                header?: never;
                path: {
                    anime_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rating summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RatingSummaryResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Submit or update a rating for an anime */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    anime_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RateRequest"];
                };
            };
            responses: {
                /** @description Updated rating summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RatingSummary"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error?: {
                code?: string;
                message?: string;
                details?: Record<string, never>;
                request_id?: string;
            };
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            username: string;
            password: string;
        };
        LoginRequest: {
            /** @description Email or username */
            login: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        UserInfo: {
            id?: string;
            email?: string;
            username?: string;
            /** Format: date-time */
            created_at?: string;
        };
        AuthResponse: {
            user?: components["schemas"]["UserInfo"];
            access_token?: string;
            refresh_token?: string;
            expires_in?: number;
        };
        MeResponse: {
            user_id?: string;
            email?: string;
            username?: string;
        };
        SearchResponse: {
            hits?: Record<string, never>[];
            total?: number;
        };
        PlaybackSource: {
            url?: string;
            quality?: string;
            is_m3u8?: boolean;
        };
        PlaybackTrack: {
            kind?: string;
            file?: string;
            label?: string;
            language?: string;
        };
        IntroOutro: {
            start?: number;
            end?: number;
        };
        WatchResponse: {
            sources?: components["schemas"]["PlaybackSource"][];
            tracks?: components["schemas"]["PlaybackTrack"][];
            intro?: components["schemas"]["IntroOutro"];
            outro?: components["schemas"]["IntroOutro"];
            signed_playback_url?: string;
        };
        SourcesResponse: {
            sources?: components["schemas"]["PlaybackSource"][];
            tracks?: components["schemas"]["PlaybackTrack"][];
            intro?: components["schemas"]["IntroOutro"];
            outro?: components["schemas"]["IntroOutro"];
            headers?: {
                [key: string]: string;
            };
            provider_episode_id?: string;
        };
        UpsertProgressRequest: {
            episode_id: string;
            position_seconds: number;
            duration_seconds?: number;
            /** Format: int64 */
            client_ts_ms?: number;
        };
        EpisodeProgress: {
            episode_id?: string;
            position_seconds?: number;
            duration_seconds?: number;
            completed?: boolean;
            /** Format: int64 */
            updated_at_ms?: number;
            /** Format: int64 */
            client_ts_ms?: number;
        };
        ContinueWatchingResponse: {
            items?: {
                episode?: {
                    episode_id?: string;
                    anime_id?: string;
                    number?: number;
                    title?: string;
                    aired_at?: string;
                };
                progress?: components["schemas"]["EpisodeProgress"];
            }[];
            limit?: number;
            next_cursor?: string;
        };
        RatingSummary: {
            anime_id?: string;
            average_score?: number;
            total_ratings?: number;
        };
        RatingSummaryResponse: {
            anime_id?: string;
            average_score?: number;
            total_ratings?: number;
            user_score?: number | null;
        };
        RateRequest: {
            user_id: string;
            score: number;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
