ALTER TABLE anime ADD COLUMN IF NOT EXISTS title_english TEXT NOT NULL DEFAULT '';
ALTER TABLE anime ADD COLUMN IF NOT EXISTS title_japanese TEXT NOT NULL DEFAULT '';
ALTER TABLE anime ADD COLUMN IF NOT EXISTS score REAL NOT NULL DEFAULT 0;
