run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - gocritic
    - bodyclose
    - goconst
    - gofmt
    - goimports
    - misspell
    - unparam

linters-settings:
  goimports:
    local-prefixes: github.com/example/anime-platform
  revive:
    rules:
      - name: var-naming
      - name: errorf
      - name: error-strings
      - name: package-comments
        disabled: true

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - errcheck

